### ISSUE TITLE
Import highlight time to json file, send to backend

### ISSUE THREAD

**Issue by christopherlavallee** [auto-highlighter/auto-highlighter-front-end#3]
Figure out how to wrap data in json file and send to backend

**Comment by RyanCallahan312** [comment]
For making the request [Fetch Api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)

For making Json to send [JSON Built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON)
